[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["backend"]
known_third_party = ["fastapi", "sqlalchemy", "sqlmodel", "pydantic", "bcrypt", "jose"]
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "I", "B", "UP", "N", "ASYNC", "A", "C4", "DTZ", "TID", "ARG", "SIM"]
ignore = ["E501"]  # Black handles line length
fix = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # allow unused imports in package __init__

[tool.mypy]
python_version = "3.11"
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
strict_optional = true

[tool.pytest.ini_options]
testpaths = ["backend/tests"]
pythonpath = ["."]
